title: Your Name
description: Data Analyst | SQL · Python · Excel . Power
url: "https://justsharon.github.io"
baseurl: "/sharonodiwa"

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock